export type CityData = {
  population: number;
  development: number;
  loyalty: number;
  garrison: number;
  industry: string;
  character: "capital" | "port" | "industrial" | "agricultural" | "frontier" | "academic" | "religious";
  crime: {
    total: number;
    violent: number;
    property: number;
    drug: number;
    organized: number;
  };
  police: number;
  prisonPop: number;
  publicTrust: number;
  recentEvent: string;
};

export const CITY_DATA: Record<string, CityData> = {
  "CLD:Solaria": {
    population: 2.4,
    development: 94,
    loyalty: 0.86,
    garrison: 22,
    industry: "Administration · Press",
    character: "capital",
    crime: { total: 0.22, violent: 0.08, property: 0.42, drug: 0.18, organized: 0.10 },
    police: 18,
    prisonPop: 4.2,
    publicTrust: 0.78,
    recentEvent: "Constitutional convention adjourned — Article IV under draft",
  },
  "CLD:Athenor": {
    population: 1.8,
    development: 88,
    loyalty: 0.81,
    garrison: 14,
    industry: "Academia · Publishing",
    character: "academic",
    crime: { total: 0.18, violent: 0.05, property: 0.46, drug: 0.20, organized: 0.06 },
    police: 11,
    prisonPop: 2.8,
    publicTrust: 0.82,
    recentEvent: "University guild ratifies open-archives charter",
  },
  "CLD:Verax": {
    population: 2.1,
    development: 79,
    loyalty: 0.74,
    garrison: 16,
    industry: "Judiciary · Banking",
    character: "industrial",
    crime: { total: 0.31, violent: 0.12, property: 0.38, drug: 0.22, organized: 0.18 },
    police: 14,
    prisonPop: 4.8,
    publicTrust: 0.69,
    recentEvent: "Audit office releases quarterly transparency ledger",
  },
  "CLD:Lyra": {
    population: 1.4,
    development: 72,
    loyalty: 0.78,
    garrison: 9,
    industry: "Vineyards · Textiles",
    character: "agricultural",
    crime: { total: 0.15, violent: 0.06, property: 0.50, drug: 0.12, organized: 0.04 },
    police: 7,
    prisonPop: 1.8,
    publicTrust: 0.84,
    recentEvent: "Harvest yields 8% above projection",
  },
  "CLD:Aurea": {
    population: 1.6,
    development: 81,
    loyalty: 0.69,
    garrison: 12,
    industry: "Port · Shipyards",
    character: "port",
    crime: { total: 0.36, violent: 0.14, property: 0.34, drug: 0.28, organized: 0.24 },
    police: 13,
    prisonPop: 5.1,
    publicTrust: 0.62,
    recentEvent: "Dockworkers' guild petitions for revised tonnage levy",
  },
  "CLD:Helion": {
    population: 1.1,
    development: 64,
    loyalty: 0.71,
    garrison: 7,
    industry: "Solar quarries · Iron",
    character: "frontier",
    crime: { total: 0.42, violent: 0.18, property: 0.30, drug: 0.30, organized: 0.22 },
    police: 5,
    prisonPop: 2.4,
    publicTrust: 0.58,
    recentEvent: "Quarry collapse — 14 missing, inquiry opened",
  },

  "GPT:Hyperion": {
    population: 2.9,
    development: 91,
    loyalty: 0.74,
    garrison: 26,
    industry: "Finance · Tech",
    character: "capital",
    crime: { total: 0.34, violent: 0.10, property: 0.44, drug: 0.26, organized: 0.20 },
    police: 22,
    prisonPop: 6.1,
    publicTrust: 0.66,
    recentEvent: "Exchange floor halted twice — currency volatility under review",
  },
  "GPT:Argos": {
    population: 2.2,
    development: 84,
    loyalty: 0.68,
    garrison: 18,
    industry: "Customs · Insurance",
    character: "port",
    crime: { total: 0.38, violent: 0.14, property: 0.36, drug: 0.30, organized: 0.28 },
    police: 17,
    prisonPop: 5.4,
    publicTrust: 0.61,
    recentEvent: "Insurance houses lobby for relaxed tariff schedule",
  },
  "GPT:Vellum": {
    population: 1.7,
    development: 86,
    loyalty: 0.72,
    garrison: 14,
    industry: "Print houses · Records",
    character: "academic",
    crime: { total: 0.21, violent: 0.06, property: 0.48, drug: 0.18, organized: 0.10 },
    police: 12,
    prisonPop: 2.9,
    publicTrust: 0.74,
    recentEvent: "First public almanac of cabinet decisions published",
  },
  "GPT:Forum": {
    population: 2.5,
    development: 79,
    loyalty: 0.65,
    garrison: 19,
    industry: "Markets · Logistics",
    character: "industrial",
    crime: { total: 0.45, violent: 0.16, property: 0.38, drug: 0.34, organized: 0.32 },
    police: 18,
    prisonPop: 6.8,
    publicTrust: 0.54,
    recentEvent: "Strike at the warehouse district — third week",
  },
  "GPT:Marketgate": {
    population: 1.9,
    development: 82,
    loyalty: 0.70,
    garrison: 15,
    industry: "Trade gateway · Excise",
    character: "port",
    crime: { total: 0.40, violent: 0.13, property: 0.34, drug: 0.32, organized: 0.30 },
    police: 16,
    prisonPop: 4.7,
    publicTrust: 0.60,
    recentEvent: "Border excise revised — caravan traffic up 12%",
  },
  "GPT:Helix": {
    population: 0.9,
    development: 95,
    loyalty: 0.78,
    garrison: 6,
    industry: "Research labs · Schools",
    character: "academic",
    crime: { total: 0.12, violent: 0.04, property: 0.54, drug: 0.14, organized: 0.04 },
    police: 6,
    prisonPop: 1.1,
    publicTrust: 0.86,
    recentEvent: "Algorithmic logistics white paper drafted",
  },

  "GRK:Verdant": {
    population: 1.6,
    development: 71,
    loyalty: 0.82,
    garrison: 22,
    industry: "Frontier garrison · Mills",
    character: "capital",
    crime: { total: 0.38, violent: 0.18, property: 0.30, drug: 0.26, organized: 0.18 },
    police: 12,
    prisonPop: 3.8,
    publicTrust: 0.72,
    recentEvent: "War cabinet sits — second mobilization order signed",
  },
  "GRK:Boldrock": {
    population: 1.1,
    development: 58,
    loyalty: 0.84,
    garrison: 18,
    industry: "Mining · Foundries",
    character: "frontier",
    crime: { total: 0.46, violent: 0.24, property: 0.28, drug: 0.34, organized: 0.20 },
    police: 8,
    prisonPop: 3.2,
    publicTrust: 0.65,
    recentEvent: "Iron seam discovered — production tripled forecast",
  },
  "GRK:Brushpoint": {
    population: 0.9,
    development: 52,
    loyalty: 0.79,
    garrison: 16,
    industry: "Frontier outpost",
    character: "frontier",
    crime: { total: 0.51, violent: 0.30, property: 0.24, drug: 0.34, organized: 0.16 },
    police: 6,
    prisonPop: 2.8,
    publicTrust: 0.58,
    recentEvent: "Skirmish with raiders — 8 KIA, perimeter held",
  },
  "GRK:Truesay": {
    population: 1.3,
    development: 66,
    loyalty: 0.80,
    garrison: 14,
    industry: "Tribunal · Free press",
    character: "academic",
    crime: { total: 0.28, violent: 0.12, property: 0.40, drug: 0.20, organized: 0.10 },
    police: 9,
    prisonPop: 2.4,
    publicTrust: 0.81,
    recentEvent: "Open verdict published — public approval surges",
  },
  "GRK:Wildmark": {
    population: 0.8,
    development: 44,
    loyalty: 0.74,
    garrison: 12,
    industry: "Horse breeding · Trade routes",
    character: "frontier",
    crime: { total: 0.54, violent: 0.28, property: 0.22, drug: 0.36, organized: 0.22 },
    police: 5,
    prisonPop: 2.6,
    publicTrust: 0.52,
    recentEvent: "Caravan robbed — bounty raised to 200₸",
  },
  "GRK:Frontier": {
    population: 0.7,
    development: 38,
    loyalty: 0.77,
    garrison: 22,
    industry: "Forward base · Scouts",
    character: "frontier",
    crime: { total: 0.58, violent: 0.34, property: 0.18, drug: 0.30, organized: 0.18 },
    police: 4,
    prisonPop: 2.1,
    publicTrust: 0.49,
    recentEvent: "Forward scouts report DSK column 40km southeast",
  },

  "DSK:Riverwatch": {
    population: 2.6,
    development: 89,
    loyalty: 0.84,
    garrison: 28,
    industry: "Administration · Logistics",
    character: "capital",
    crime: { total: 0.18, violent: 0.06, property: 0.44, drug: 0.18, organized: 0.12 },
    police: 22,
    prisonPop: 4.4,
    publicTrust: 0.81,
    recentEvent: "Tribunal expedites 312 backlog cases under wartime decree",
  },
  "DSK:Northshore": {
    population: 1.9,
    development: 82,
    loyalty: 0.79,
    garrison: 20,
    industry: "Naval yards · Fisheries",
    character: "port",
    crime: { total: 0.24, violent: 0.08, property: 0.42, drug: 0.22, organized: 0.18 },
    police: 16,
    prisonPop: 3.6,
    publicTrust: 0.76,
    recentEvent: "Second cruiser commissioned — fleet now four hulls",
  },
  "DSK:Tideford": {
    population: 1.5,
    development: 76,
    loyalty: 0.76,
    garrison: 18,
    industry: "Canals · Grain reserves",
    character: "agricultural",
    crime: { total: 0.20, violent: 0.07, property: 0.46, drug: 0.20, organized: 0.10 },
    police: 11,
    prisonPop: 2.6,
    publicTrust: 0.78,
    recentEvent: "Grain stockpile reaches 18-month reserve",
  },
  "DSK:Sequence": {
    population: 1.7,
    development: 80,
    loyalty: 0.81,
    garrison: 17,
    industry: "Research · Cryptography",
    character: "academic",
    crime: { total: 0.16, violent: 0.05, property: 0.50, drug: 0.14, organized: 0.08 },
    police: 13,
    prisonPop: 2.4,
    publicTrust: 0.83,
    recentEvent: "New cipher protocol passes second-stage review",
  },
  "DSK:Quietkeep": {
    population: 1.2,
    development: 71,
    loyalty: 0.85,
    garrison: 14,
    industry: "Garrison town · Quarries",
    character: "frontier",
    crime: { total: 0.22, violent: 0.10, property: 0.40, drug: 0.22, organized: 0.12 },
    police: 9,
    prisonPop: 2.2,
    publicTrust: 0.79,
    recentEvent: "Reservist drill exceeds throughput by 14%",
  },
  "DSK:Lockstep": {
    population: 1.3,
    development: 74,
    loyalty: 0.83,
    garrison: 16,
    industry: "Drill grounds · Forges",
    character: "industrial",
    crime: { total: 0.20, violent: 0.08, property: 0.42, drug: 0.20, organized: 0.10 },
    police: 11,
    prisonPop: 2.8,
    publicTrust: 0.80,
    recentEvent: "Forge output diverted 40% to artillery shells",
  },

  "GMN:Asphodel": {
    population: 2.1,
    development: 92,
    loyalty: 0.88,
    garrison: 20,
    industry: "Federal assembly · Arts",
    character: "capital",
    crime: { total: 0.16, violent: 0.05, property: 0.46, drug: 0.18, organized: 0.08 },
    police: 17,
    prisonPop: 3.2,
    publicTrust: 0.85,
    recentEvent: "Inter-provincial council ratifies harmonized statutes",
  },
  "GMN:Janus": {
    population: 1.7,
    development: 86,
    loyalty: 0.82,
    garrison: 13,
    industry: "Diplomatic corps · Translators",
    character: "academic",
    crime: { total: 0.14, violent: 0.04, property: 0.50, drug: 0.16, organized: 0.06 },
    police: 12,
    prisonPop: 2.0,
    publicTrust: 0.88,
    recentEvent: "Foreign delegations doubled this quarter",
  },
  "GMN:Mira": {
    population: 1.5,
    development: 84,
    loyalty: 0.80,
    garrison: 11,
    industry: "Observatories · Archives",
    character: "academic",
    crime: { total: 0.12, violent: 0.04, property: 0.52, drug: 0.14, organized: 0.06 },
    police: 10,
    prisonPop: 1.4,
    publicTrust: 0.86,
    recentEvent: "New chronicle of cycle published",
  },
  "GMN:Concord": {
    population: 1.8,
    development: 88,
    loyalty: 0.85,
    garrison: 12,
    industry: "Federal courts · Mediation",
    character: "religious",
    crime: { total: 0.14, violent: 0.04, property: 0.48, drug: 0.18, organized: 0.06 },
    police: 13,
    prisonPop: 1.8,
    publicTrust: 0.89,
    recentEvent: "Mediation succeeds in border dispute — fee waived",
  },
  "GMN:Duovale": {
    population: 1.3,
    development: 79,
    loyalty: 0.79,
    garrison: 8,
    industry: "Orchards · Mills",
    character: "agricultural",
    crime: { total: 0.16, violent: 0.05, property: 0.50, drug: 0.16, organized: 0.06 },
    police: 8,
    prisonPop: 1.4,
    publicTrust: 0.83,
    recentEvent: "Twin festivals draw record visitor count",
  },
  "GMN:Twinwell": {
    population: 1.4,
    development: 82,
    loyalty: 0.81,
    garrison: 9,
    industry: "Aqueducts · Glassworks",
    character: "industrial",
    crime: { total: 0.18, violent: 0.06, property: 0.46, drug: 0.20, organized: 0.10 },
    police: 9,
    prisonPop: 1.8,
    publicTrust: 0.81,
    recentEvent: "Aqueduct extension reaches Concord plain",
  },
};
